# Generated by Django 4.2.18 on 2025-01-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsuggestion",
            name="related_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggested_packs",
                to="gallery.model",
            ),
        ),
        migrations.AlterField(
            model_name="contentsuggestion",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contentsuggestion",
            name="pack_photos",
            field=models.FileField(blank=True, null=True, upload_to="suggested_packs/"),
        ),
    ]
